# Site settings
title: "Zheln Systematic Review Appraisals"
email: pavel@zheln.com
description: "A crowdfunded project to monitor, critically appraise, & sort by specialty all systematic reviews on PubMed. Biweekly updates."
baseurl: ""
url: "https://zheln.com"
title_description: "I check <a href=\"https://pubmed.gov\">PubMed</a> for updates in the <a href=\"https://github.com/p1m-ortho/qs-global-ortho-search-queries/blob/global-sr-query/README.md\">Systematic Review Subset</a>, sort them by specialty and critically appraise the most appealing reviews twice a week. My appraisals are very thorough, see <a href=\"https://github.com/p1m-ortho/qs-global-ortho-search-queries/blob/global-sr-query/README.md\">methods</a> (academic publication in the works). This is independent research supported by crowdfunding only. Please consider sending me $1 via <a href=\"https://paypal.me/pjelnov\">PayPal</a> or buying a $1 to $5 subscription on <a href=\"https://patreon.com/zheln\">Patreon</a>, where you can also learn more about myself."
title_image: /favicons/android-chrome-512x512.png
google_analytics: "UA-122303329-3"
disqus_account: 
github_repository: https://github.com/drzhelnov/zheln.github.io
addthis_id: ra-5eb4ca836b1983cd
post_limit: 3
paginate: 4
status_tags:
  - awaiting appraisal
  - awaiting crowdfunding
  - appraisal in progress
  - appraisal complete
search_placeholder: "Type a systematic review PMID, DOI, title, etc."
search_results_container: "Start typing to find an appraisal of a systematic review. Only the first 10 records will be displayed."
specialty_page_headline: "By AMA Specialty"
specialty_page_no_posts: "Unfortunately, no posts have been tagged yet with this specialty.<br />Please come back later; or consider making a donation as low as $1 to support my processing of thousands of records weekly either on <a href=\"https://patreon.com/zheln\">Patreon</a> or via <a href=\"https://paypal.me/pjelnov\">Paypal</a>.<br />Also, you can browse other specialties using the tag cloud below or look for appraisals directly using the search box.<br />In any case, you are welcome to get in touch with me by <a href=\"mailto:pavel@zheln.com\">email</a> or using any of my social links below."

# Specialty tags

ACA: "Adult Cardiothoracic Anesthesiology"
ADL: "Adolescent Medicine"
ADM: "Addiction Medicine"
ADP: "Addiction Psychiatry"
AHF: "Advanced Heart Failure & Transplant Cardiology"
AI: "Allergy & Immunology"
ALI: "Clinical Laboratory Immunology"
AM: "Aerospace Medicine"
AN: "Anesthesiology"
AR: "Abdominal Radiology"
AS: "Abdominal Surgery"
ASO: "Advanced Surgical Oncology"
BBK: "Blood Banking/Transfusion Medicine"
BIN: "Brain Injury Medicine"
CAP: "Child Abuse Pediatrics"
CBG: "Clinical Biochemical Genetics"
CCG: "Clinical Cytogenetics"
CCM: "Critical Care Medicine"
CCP: "Pediatric Critical Care Medicine"
CCS: "Surgical Critical Care"
CD: "Cardiovascular Diseases"
CFS: "Craniofacial Surgery"
CG: "Clinical Genetics"
CHD: "Adult Congenital Heart Disease"
CHN: "Child Neurology"
CHP: "Child & Adolescent Psychiatry"
CHS: "Congenital Cardiac Surgery"
CIM: "Clinical Informatics"
CMG: "Clinical Molecular Genetics"
CN: "Clinical Neurophysiology"
CRS: "Colon & Rectal Surgery"
CS: "Cosmetic Surgery"
CTR: "Cardiothoracic Radiology"
D: "Dermatology"
DBP: "Developmental-Behavioral Pediatrics"
DDL: "Clinical & Laboratory Dermatological Immunology"
DIA: "Diabetes"
DMP: "Dermatopathology"
DR: "Diagnostic Radiology"
DS: "Dermatologic Surgery"
EM: "Emergency Medicine"
EMS: "Emergency Medical Services"
END: "Endocrinology, Diabetes, & Metabolism"
EP: "Epidemiology"
EPL: "Epilepsy"
ESN: "Endovascular Surgical Neuroradiology"
FM: "Family Medicine"
FOP: "Forensic Pathology"
FPR: "Female Pelvic Medicine & Reconstructive Surgery"
FPS: "Facial Plastic Surgery"
GE: "Gastroenterology"
GO: "Gynecological Oncology"
GP: "General Practice"
GS: "General Surgery"
GYN: "Gynecology"
HEM: "Hematology"
HEP: "Hepatology"
HNS: "Head and Neck Surgery"
HO: "Hematology/Oncology"
HPM: "Hospice & Palliative Medicine"
HS: "Hand Surgery"
IC: "Interventional Cardiology"
ICE: "Cardiac Electrophysiology"
ID: "Infectious Disease"
IG: "Immunology"
IM: "Internal Medicine"
IMG: "Geriatric Medicine"
LM: "Legal Medicine"
MBG: "Medical Biochemical Genetics"
MDM: "Medical Management"
MDP: "Medical Physics"
MFM: "Maternal & Fetal Medicine"
MG: "Medical Genetics"
MGP: "Molecular Genetic Pathology"
MM: "Medical Microbiology"
MSR: "Musculoskeletal Radiology"
N: "Neurology"
NC: "Nuclear Cardiology"
NDN: "Neurodevelopmental Disabilities"
NEP: "Nephrology"
NM: "Nuclear Medicine"
NMN: "Neuromuscular Medicine"
NONO: "Neurotology"
NP: "Neuropathology"
NPM: "Neonatal-Perinatal Medicine"
NS: "Neurological Surgery"
NTR: "Nutrition"
NUP: "Neuropsychiatry"
OAN: "Obstetric Anesthesiology"
OAR: "Adult Reconstructive Orthopedics"
OBG: "Obstetrics & Gynecology"
OFA: "Foot & Ankle Orthopedics"
OM: "Occupational Medicine"
OMF: "Oral & Maxillofacial Surgery"
OMM: "Osteopathic Manipulative Medicine"
OMO: "Musculoskeletal Oncology"
ONON: "Medical Oncology"
ONM: "Osteopathic Neuromusculoskeletal Medicine"
OP: "Pediatric Orthopedics"
OPH: "Ophthalmology"
OPR: "Ophthalmic Plastic & Reconstructive Surgery"
ORS: "Orthopedic Surgery"
OSS: "Orthopedic Spine Surgery"
OTO: "Otolaryngology"
OTR: "Orthopedic Trauma"
P: "Psychiatry"
PA: "Clinical Pharmacology"
PAN: "Pediatric Anesthesiology"
PCC: "Pulmonary Critical Care Medicine"
PCH: "Chemical Pathology"
PCP: "Cytopathology"
PCS: "Pediatric Cardiothoracic Surgery"
PD: "Pediatrics"
PDA: "Pediatric Allergy"
PDC: "Pediatric Cardiology"
PDD: "Pediatric Dermatology"
PDE: "Pediatric Endocrinology"
PDI: "Pediatric Infectious Diseases"
PDO: "Pediatric Otolaryngology"
PDP: "Pediatric Pulmonology"
PDR: "Pediatric Radiology"
PDS: "Pediatric Surgery"
PEM: "Pediatric Emergency Medicine"
PFP: "Forensic Psychiatry"
PG: "Pediatric Gastroenterology"
PHE: "Pediatric Hospital Medicine"
PHL: "Phlebology"
PHM: "Pharmaceutical Medicine"
PHO: "Pediatric Hematology/Oncology"
PHP: "Public Health & General Preventive Medicine"
PM: "Physical Medicine & Rehabilitation"
PMM: "Pain Medicine"
PN: "Pediatric Nephrology"
PO: "Pediatric Ophthalmology"
PP: "Pediatric Pathology"
PPR: "Pediatric Rheumatology"
PRD: "Procedural Dermatology"
PRS: "Sports Medicine"
PS: "Plastic Surgery"
PSH: "Plastic Head and Neck Surgery"
PTH: "Anatomic/Clinical Pathology"
PTP: "Pediatric Transplant Hepatology"
PTX: "Medical Toxicology"
PUD: "Pulmonary Disease"
PYA: "Psychoanalysis"
PYG: "Geriatric Psychiatry"
PYM: "Psychosomatic Medicine"
R: "Radiology"
REN: "Reproductive Endocrinology & Infertility"
RHU: "Rheumatology"
RNR: "Neuroradiology"
RO: "Radiation Oncology"
RP: "Radiological Physics"
RPM: "Pediatric Rehabilitation Medicine"
SCI: "Spinal Cord Injury"
SME: "Sleep Medicine"
SO: "Surgical Oncology"
SP: "Selective Pathology"
THP: "Transplant Hepatology"
TRS: "Trauma Surgery"
TS: "Thoracic Surgery"
TTS: "Transplant Surgery"
U: "Urology"
UCM: "Urgent Care Medicine"
UM: "Undersea & Hyperbaric Medicine"
UP: "Pediatric Urology"
VIR: "Vascular & Interventional Radiology"
VIR: "Vascular & Interventional Radiology"
VM: "Vascular Medicine"
VN: "Vascular Neurology"
VS: "Vascular Surgery"

# Social usernames/URLs
twitter_username: drzhelnov
github_username: pussiatoday
instagram_username: igzheln
reddit_username:
telegram_username: tgzheln
patreon_username: zheln
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link: https://www.facebook.com/drzhelnov

# Footer
footer_left: "Website template Carte Noire made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>—Licensed under <a href=\"https://raw.githubusercontent.com/jacobtomlinson/carte-noire/gh-pages/LICENSE\">GPL v3</a>.<br />Original Woodpecker Icon by <a href=\"https://thenounproject.com/parkasever/\">Anton</a>—Licensed under <a href=\"https://creativecommons.org/licenses/by-sa/3.0/legalcode\">CC BY 3.0</a>."
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i><br />&copy; <a href=\"https://zheln.com\">Zheln</a>, 2020"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]