# Site settings
title: "Zheln"
email: pavel@zheln.com
description: "Weekly updates on high-quality and impactful health research. Methods: https://doi.org/10.31222/osf.io/y2nrb"
baseurl: ""
url: "https://zheln.com"
whitepaper: "https://doi.org/10.31222/osf.io/y2nrb"
zaas: "https://zheln.com/summary/2022/04/06/suppl/#zheln-as-service"
cv: "https://drzhelnov.github.io"

#title_description: ""
title_image: /favicons/android-chrome-512x512.png
google_analytics: "G-SH5X4JEMEM"
disqus_account: 
#github_repository: https://github.com/drzhelnov/zheln.github.io
addthis_id: ra-5eb4ca836b1983cd
post_limit: 3
paginate: 4
status_tags:
  - awaiting appraisal
  - awaiting crowdfunding
  - appraisal in progress
  - appraisal complete
search_placeholder: "Type exact text to find in a post, a target article DOI, etc."
search_results_container: "Start typing to search Zheln content. Only the first 10 posts will be displayed."
search_no_results_text: "Content not found on Zheln or has not been appraised yet"
search_href_pattern: "<a[^>]+href=\"([^\"]+)\"[^>]*>([^<]+)<\/a>"
search_href_replacement: '\2 (\1)'
specialty_page_headline: "By AMA Specialty"
specialty_page_no_posts: "<ul><li>Unfortunately, no posts have been tagged with this specialty yet.</li><li>Please come back later, or consider making a donation as small as $1 to support my processing of thousands of records weekly either on <a href=\"https://patreon.com/zheln\">Patreon</a>, <a href=\"https://github.com/sponsors/drzhelnov\">GitHub Sponsors</a>, <a href=\"https://opencollective.com/zheln\">Open Collective</a>.</li><li>Also, you can <a href=\"/browse/\">browse other specialties</a> using the tag cloud or <a href=\"/search/\">look for appraisals directly</a> using the search box.</li><li>In any case, you are welcome to get in touch with me by <a href=\"mailto:pavel@zheln.com\">email</a> or using any of my social links below.</li></ul>"
ssb_link: "https://doi.org/10.17605/osf.io/z3ju7"
latest_headline: "Latest Research Stories"
day_page_headline: "From Replicated PubMed Systematic Subset"
day_page_header: "Zheln Records"
day_page_before_label: "« Day Before"
day_page_next_label: "Next Day »"
record_awaiting_appraisal: "Record Awaiting Appraisal"
prev_post_label: "« Previous Post"
next_post_label: "Next Post »"
no_next_post: "No Newer Posts Yet"
step_2_fail: "❌ Does Not Meet Shojania &amp; Bero 2001 True Positive Criteria for Systematic Reviews by Neither Title nor Abstract"
step_2_waiting: "🔄 Meets Shojania &amp; Bero 2001 True Positive Criteria for Systematic Reviews by Either Title or Abstract?"
appraisal_log:
  total: "Total"
  primary-appraisal: "Screened"
  percent-total: "% of Total"
  fail: "❌ Fail"
  pass: "✅ Pass"
  pass-rate: "Pass Rate"
  number-needed-appraise: "Number Needed to Enrol in Selection"

# Specialty tags

ACA: "Adult Cardiothoracic Anesthesiology"
ADL: "Adolescent Medicine"
ADM: "Addiction Medicine"
ADP: "Addiction Psychiatry"
AHF: "Advanced Heart Failure & Transplant Cardiology"
AI: "Allergy & Immunology"
ALI: "Clinical Laboratory Immunology"
AM: "Aerospace Medicine"
AN: "Anesthesiology"
AR: "Abdominal Radiology"
AS: "Abdominal Surgery"
ASO: "Advanced Surgical Oncology"
BBK: "Blood Banking/Transfusion Medicine"
BIN: "Brain Injury Medicine"
CAP: "Child Abuse Pediatrics"
CBG: "Clinical Biochemical Genetics"
CCG: "Clinical Cytogenetics"
CCM: "Critical Care Medicine"
CCP: "Pediatric Critical Care Medicine"
CCS: "Surgical Critical Care"
CD: "Cardiovascular Diseases"
CFS: "Craniofacial Surgery"
CG: "Clinical Genetics"
CHD: "Adult Congenital Heart Disease"
CHN: "Child Neurology"
CHP: "Child & Adolescent Psychiatry"
CHS: "Congenital Cardiac Surgery"
CIM: "Clinical Informatics"
CMG: "Clinical Molecular Genetics"
CN: "Clinical Neurophysiology"
CRS: "Colon & Rectal Surgery"
CS: "Cosmetic Surgery"
CTR: "Cardiothoracic Radiology"
D: "Dermatology"
DBP: "Developmental-Behavioral Pediatrics"
DDL: "Clinical & Laboratory Dermatological Immunology"
DIA: "Diabetes"
DMP: "Dermatopathology"
DR: "Diagnostic Radiology"
DS: "Dermatologic Surgery"
EM: "Emergency Medicine"
EMS: "Emergency Medical Services"
END: "Endocrinology, Diabetes, & Metabolism"
EP: "Epidemiology"
EPL: "Epilepsy"
ESN: "Endovascular Surgical Neuroradiology"
FM: "Family Medicine"
FOP: "Forensic Pathology"
FPR: "Female Pelvic Medicine & Reconstructive Surgery"
FPS: "Facial Plastic Surgery"
GE: "Gastroenterology"
GO: "Gynecological Oncology"
GP: "General Practice"
GS: "General Surgery"
GYN: "Gynecology"
HEM: "Hematology"
HEP: "Hepatology"
HNS: "Head and Neck Surgery"
HO: "Hematology/Oncology"
HPM: "Hospice & Palliative Medicine"
HS: "Hand Surgery"
IC: "Interventional Cardiology"
ICE: "Cardiac Electrophysiology"
ID: "Infectious Disease"
IG: "Immunology"
IM: "Internal Medicine"
IMG: "Geriatric Medicine"
LM: "Legal Medicine"
MBG: "Medical Biochemical Genetics"
MDM: "Medical Management"
MDP: "Medical Physics"
MFM: "Maternal & Fetal Medicine"
MG: "Medical Genetics"
MGP: "Molecular Genetic Pathology"
MM: "Medical Microbiology"
MSR: "Musculoskeletal Radiology"
N: "Neurology"
NC: "Nuclear Cardiology"
NDN: "Neurodevelopmental Disabilities"
NEP: "Nephrology"
NM: "Nuclear Medicine"
NMN: "Neuromuscular Medicine"
NONO: "Neurotology"
NP: "Neuropathology"
NPM: "Neonatal-Perinatal Medicine"
NS: "Neurological Surgery"
NTR: "Nutrition"
NUP: "Neuropsychiatry"
OAN: "Obstetric Anesthesiology"
OAR: "Adult Reconstructive Orthopedics"
OBG: "Obstetrics & Gynecology"
OFA: "Foot & Ankle Orthopedics"
OM: "Occupational Medicine"
OMF: "Oral & Maxillofacial Surgery"
OMM: "Osteopathic Manipulative Medicine"
OMO: "Musculoskeletal Oncology"
ONON: "Medical Oncology"
ONM: "Osteopathic Neuromusculoskeletal Medicine"
OP: "Pediatric Orthopedics"
OPH: "Ophthalmology"
OPR: "Ophthalmic Plastic & Reconstructive Surgery"
ORS: "Orthopedic Surgery"
OSS: "Orthopedic Spine Surgery"
OTO: "Otolaryngology"
OTR: "Orthopedic Trauma"
P: "Psychiatry"
PA: "Clinical Pharmacology"
PAN: "Pediatric Anesthesiology"
PCC: "Pulmonary Critical Care Medicine"
PCH: "Chemical Pathology"
PCP: "Cytopathology"
PCS: "Pediatric Cardiothoracic Surgery"
PD: "Pediatrics"
PDA: "Pediatric Allergy"
PDC: "Pediatric Cardiology"
PDD: "Pediatric Dermatology"
PDE: "Pediatric Endocrinology"
PDI: "Pediatric Infectious Diseases"
PDO: "Pediatric Otolaryngology"
PDP: "Pediatric Pulmonology"
PDR: "Pediatric Radiology"
PDS: "Pediatric Surgery"
PEM: "Pediatric Emergency Medicine"
PFP: "Forensic Psychiatry"
PG: "Pediatric Gastroenterology"
PHE: "Pediatric Hospital Medicine"
PHL: "Phlebology"
PHM: "Pharmaceutical Medicine"
PHO: "Pediatric Hematology/Oncology"
PHP: "Public Health & General Preventive Medicine"
PM: "Physical Medicine & Rehabilitation"
PMM: "Pain Medicine"
PN: "Pediatric Nephrology"
PO: "Pediatric Ophthalmology"
PP: "Pediatric Pathology"
PPR: "Pediatric Rheumatology"
PRD: "Procedural Dermatology"
PRS: "Sports Medicine"
PS: "Plastic Surgery"
PSH: "Plastic Head and Neck Surgery"
PTH: "Anatomic/Clinical Pathology"
PTP: "Pediatric Transplant Hepatology"
PTX: "Medical Toxicology"
PUD: "Pulmonary Disease"
PYA: "Psychoanalysis"
PYG: "Geriatric Psychiatry"
PYM: "Psychosomatic Medicine"
R: "Radiology"
REN: "Reproductive Endocrinology & Infertility"
RHU: "Rheumatology"
RNR: "Neuroradiology"
RO: "Radiation Oncology"
RP: "Radiological Physics"
RPM: "Pediatric Rehabilitation Medicine"
SCI: "Spinal Cord Injury"
SME: "Sleep Medicine"
SO: "Surgical Oncology"
SP: "Selective Pathology"
THP: "Transplant Hepatology"
TRS: "Trauma Surgery"
TS: "Thoracic Surgery"
TTS: "Transplant Surgery"
U: "Urology"
UCM: "Urgent Care Medicine"
UM: "Undersea & Hyperbaric Medicine"
UP: "Pediatric Urology"
VIR: "Vascular & Interventional Radiology"
VIR: "Vascular & Interventional Radiology"
VM: "Vascular Medicine"
VN: "Vascular Neurology"
VS: "Vascular Surgery"

# Social usernames/URLs
twitter_username: drzhelnov
github_sponsors_username: drzhelnov
#paypal_username: pjelnov
instagram_username: igzheln
reddit_username:
telegram_username: tgzheln
patreon_username:
linkedin_link: https://www.linkedin.com/company/zheln/
google_plus_link: 
stackoverflow_link: 
xing_link:
#facebook_link: https://www.facebook.com/drzhelnov
youtube_link: https://www.youtube.com/@drzhelnov
#tiktok_username: the_trash_scientist

# Footer
footer_left: "Website template Carte Noire made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>—Licensed under <a href=\"https://raw.githubusercontent.com/jacobtomlinson/carte-noire/gh-pages/LICENSE\">GPL v3</a>."
footer_right:
  pre_copy: "<i class=\"fas fa-graduation-cap\"></i> <a href=\"https://doi.org/10.31222/osf.io/y2nrb\">Methods</a> | &lt;/&gt; on <a href=\"https://github.com/drzhelnov/zheln.github.io\">GitHub</a> &nbsp;<i class=\"fa fa-github-alt\"></i><br />"
  post_copy: " | <i class=\"far fa-heart\"></i> <a href=\"https://github.com/sponsors/drzhelnov\">Support</a>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
