# Site settings
title: "Zheln"
email: pavel@zheln.com
description: "A blog to review recent systematic reviews."
baseurl: ""
url: "https://zheln.com/"
title_description: "I check <a href=\"https://pubmed.gov\">PubMed</a> for updates in the <a href=\"https://p1m.org/ssb\">Systematic Review Subset</a> and critically assess the most appealing reviews. This is independent research and my primary job. Please support me on <a href=\"https://patreon.com/zheln\">Patreon</a>, where you can also learn more about myself."
title_image: favicons/android-chrome-512x512.png
google_analytics: "UA-122303329-3"
disqus_account: 
github_repository: https://github.com/drzhelnov/zheln.github.io
addthis_id: ra-5eb4ca836b1983cd
post_limit: 3

# Social usernames/URLs
twitter_username: drzhelnov
github_username: pussiatoday
instagram_username: igzheln
reddit_username:
telegram_username: tgzheln
patreon_username: zheln
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link: https://www.facebook.com/drzhelnov

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>.<br />Original Woodpecker Icon by <a href=\"https://thenounproject.com/parkasever/\">Anton</a>—Licensed under <a href=\"https://creativecommons.org/licenses/by-sa/3.0/legalcode\">CC BY 3.0</a>."
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]