# Site settings
title: "Zheln Systematic Review Appraisals"
email: pavel@zheln.com
description: "A crowdfunded project to monitor, critically appraise, & sort by specialty all systematic reviews on PubMed. Biweekly updates."
baseurl: ""
url: "https://zheln.com/"
title_description: "I check <a href=\"https://pubmed.gov\">PubMed</a> for updates in the <a href=\"https://github.com/p1m-ortho/qs-global-ortho-search-queries/blob/global-sr-query/README.md\">Systematic Review Subset</a>, sort them by specialty and critically appraise the most appealing reviews twice a week. My appraisals are very thorough, see <a href=\"https://github.com/p1m-ortho/qs-global-ortho-search-queries/blob/global-sr-query/README.md\">methods</a> (academic publication in the works). This is independent research supported by crowdfunding only. Please consider sending me $1 via <a href=\"https://paypal.me/pjelnov\">PayPal</a> or buying a $1.2 to $6 subscription on <a href=\"https://patreon.com/zheln\">Patreon</a>, where you can also learn more about myself."
title_image: /favicons/android-chrome-512x512.png
google_analytics: "UA-122303329-3"
disqus_account: 
github_repository: https://github.com/drzhelnov/zheln.github.io
addthis_id: ra-5eb4ca836b1983cd
post_limit: 3
paginate: 4
status_tags:
  - awaiting appraisal
  - awaiting crowdfunding
  - appraisal in progress
  - appraisal complete
search_placeholder: "Type a systematic review PMID, DOI, title, etc."
search_results_container: "Start typing to find an appraisal of a systematic review. Only the first 10 records will be displayed."
specialty_page_headline: "By AMA Specialty"

# Social usernames/URLs
twitter_username: drzhelnov
github_username: pussiatoday
instagram_username: igzheln
reddit_username:
telegram_username: tgzheln
patreon_username: zheln
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link: https://www.facebook.com/drzhelnov

# Footer
footer_left: "Website template Carte Noire made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>—Licensed under <a href\"https://raw.githubusercontent.com/jacobtomlinson/carte-noire/gh-pages/LICENSE\">GPL v3</a>.<br />Original Woodpecker Icon by <a href=\"https://thenounproject.com/parkasever/\">Anton</a>—Licensed under <a href=\"https://creativecommons.org/licenses/by-sa/3.0/legalcode\">CC BY 3.0</a>."
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i><br />&copy; <a href=\"https://zheln.com\">Zheln</a>, 2020"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]