#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
git clone https://${GITHUB_TOKEN}@github.com/drzhelnov/zheln.github.io.git --branch master _site

# build with Jekyll into "_site"
bundle exec jekyll build

# push
cd _site
git config user.email "pzhelnov@p1m.org"
git config user.name "Pavel Zhelnov"
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force origin gh-pages